-- MySQL Script generated by MySQL Workbench
-- Sun Jun 14 13:22:10 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema vndb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vndb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vndb` DEFAULT CHARACTER SET utf8mb4 ;
USE `vndb` ;

-- -----------------------------------------------------
-- Table `vndb`.`char_vn_relation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vndb`.`char_vn_relation` ;

CREATE TABLE IF NOT EXISTS `vndb`.`char_vn_relation` (
  `char_id` INT NOT NULL,
  `vn_id` INT NOT NULL,
  INDEX `fk_vn_char_has_vn_vn1_idx` (`vn_id` ASC) VISIBLE,
  INDEX `fk_vn_char_has_vn_vn_char1_idx` (`char_id` ASC) VISIBLE,
  CONSTRAINT `fk_vn_char_has_vn_vn_char1`
    FOREIGN KEY (`char_id`)
    REFERENCES `vndb`.`vn_char` (`char_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vn_char_has_vn_vn1`
    FOREIGN KEY (`vn_id`)
    REFERENCES `vndb`.`vn` (`vn_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vndb`.`lang`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vndb`.`lang` ;

CREATE TABLE IF NOT EXISTS `vndb`.`lang` (
  `language_code` VARCHAR(2) NOT NULL,
  `language_name` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`language_code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vndb`.`position`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vndb`.`position` ;

CREATE TABLE IF NOT EXISTS `vndb`.`position` (
  `position_id` INT NOT NULL,
  `title` VARCHAR(250) NULL,
  `intro` TEXT NULL,
  PRIMARY KEY (`position_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vndb`.`producer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vndb`.`producer` ;

CREATE TABLE IF NOT EXISTS `vndb`.`producer` (
  `producer_id` INT NOT NULL,
  `type` VARCHAR(50) NOT NULL DEFAULT 'co',
  `en_name` VARCHAR(250) NOT NULL DEFAULT '',
  `original_name` VARCHAR(250) NOT NULL DEFAULT '',
  `alias` VARCHAR(500) NULL,
  `website` VARCHAR(250) NULL,
  `intro` TEXT NULL,
  `language_code` VARCHAR(2) NULL,
  PRIMARY KEY (`producer_id`),
  INDEX `fk_producer_language1_idx` (`language_code` ASC) VISIBLE,
  CONSTRAINT `fk_producer_language1`
    FOREIGN KEY (`language_code`)
    REFERENCES `vndb`.`lang` (`language_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vndb`.`staff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vndb`.`staff` ;

CREATE TABLE IF NOT EXISTS `vndb`.`staff` (
  `staff_id` INT NOT NULL,
  `gender` VARCHAR(7) NULL,
  `intro` TEXT NULL,
  `website` VARCHAR(250) NULL,
  `twitter` VARCHAR(250) NULL,
  PRIMARY KEY (`staff_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vndb`.`staff_stage_name`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vndb`.`staff_stage_name` ;

CREATE TABLE IF NOT EXISTS `vndb`.`staff_stage_name` (
  `staff_stage_name_id` INT NOT NULL,
  `en_stage_name` VARCHAR(250) NULL,
  `original_stage_name` VARCHAR(250) NULL,
  `staff_id` INT NOT NULL,
  PRIMARY KEY (`staff_stage_name_id`),
  INDEX `fk_staff_stage_name_staff1_idx` (`staff_id` ASC) VISIBLE,
  CONSTRAINT `fk_staff_stage_name_staff1`
    FOREIGN KEY (`staff_id`)
    REFERENCES `vndb`.`staff` (`staff_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vndb`.`vn`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vndb`.`vn` ;

CREATE TABLE IF NOT EXISTS `vndb`.`vn` (
  `vn_id` INT NOT NULL,
  `en_title` VARCHAR(250) NOT NULL DEFAULT '',
  `original_title` VARCHAR(250) NOT NULL DEFAULT '',
  `alias` VARCHAR(250) NOT NULL DEFAULT '',
  `intro` TEXT NULL DEFAULT '',
  PRIMARY KEY (`vn_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vndb`.`vn_char`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vndb`.`vn_char` ;

CREATE TABLE IF NOT EXISTS `vndb`.`vn_char` (
  `char_id` INT NOT NULL,
  `en_name` VARCHAR(250) NOT NULL DEFAULT '',
  `original_name` VARCHAR(250) NOT NULL DEFAULT '',
  `alias` VARCHAR(250) NULL DEFAULT '',
  `intro` TEXT NULL DEFAULT '',
  `gender` VARCHAR(50) NULL,
  `b_month` INT NULL DEFAULT 0,
  `b_day` INT NULL DEFAULT 0,
  `height` INT NULL,
  `weight` INT NULL,
  `blood_type` VARCHAR(7) NULL DEFAULT 'unknown',
  `age` INT NULL,
  PRIMARY KEY (`char_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vndb`.`vn_producer_relation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vndb`.`vn_producer_relation` ;

CREATE TABLE IF NOT EXISTS `vndb`.`vn_producer_relation` (
  `vn_id` INT NOT NULL,
  `producer_id` INT NOT NULL,
  INDEX `fk_vn_has_producer_producer1_idx` (`producer_id` ASC) VISIBLE,
  INDEX `fk_vn_has_producer_vn1_idx` (`vn_id` ASC) VISIBLE,
  CONSTRAINT `fk_vn_has_producer_vn1`
    FOREIGN KEY (`vn_id`)
    REFERENCES `vndb`.`vn` (`vn_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vn_has_producer_producer1`
    FOREIGN KEY (`producer_id`)
    REFERENCES `vndb`.`producer` (`producer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vndb`.`vn_release`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vndb`.`vn_release` ;

CREATE TABLE IF NOT EXISTS `vndb`.`vn_release` (
  `release_id` INT NOT NULL,
  `en_title` VARCHAR(250) NULL,
  `original_title` VARCHAR(250) NULL,
  `website` VARCHAR(250) NULL,
  `note` TEXT NULL,
  `vn_id` INT NULL,
  `language_code` VARCHAR(2) NULL,
  PRIMARY KEY (`release_id`),
  INDEX `fk_release_vn1_idx` (`vn_id` ASC) VISIBLE,
  INDEX `fk_release_language1_idx` (`language_code` ASC) VISIBLE,
  CONSTRAINT `fk_release_vn1`
    FOREIGN KEY (`vn_id`)
    REFERENCES `vndb`.`vn` (`vn_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_release_language1`
    FOREIGN KEY (`language_code`)
    REFERENCES `vndb`.`lang` (`language_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vndb`.`vn_staff_relation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vndb`.`vn_staff_relation` ;

CREATE TABLE IF NOT EXISTS `vndb`.`vn_staff_relation` (
  `vn_id` INT NOT NULL,
  `staff_id` INT NOT NULL,
  `position_id` INT NULL,
  `NOTE` TEXT NULL,
  INDEX `fk_vn_has_staff_staff1_idx` (`staff_id` ASC) VISIBLE,
  INDEX `fk_vn_has_staff_vn1_idx` (`vn_id` ASC) VISIBLE,
  INDEX `fk_vn_staff_position1_idx` (`position_id` ASC) VISIBLE,
  CONSTRAINT `fk_vn_has_staff_vn1`
    FOREIGN KEY (`vn_id`)
    REFERENCES `vndb`.`vn` (`vn_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vn_has_staff_staff1`
    FOREIGN KEY (`staff_id`)
    REFERENCES `vndb`.`staff` (`staff_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vn_staff_position1`
    FOREIGN KEY (`position_id`)
    REFERENCES `vndb`.`position` (`position_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
